1.Given a 1D array, negate all elements which are between 3 and 8, in place (not created a new array).


In [1]:
import numpy as np 
a=np.arange(0,10)
a=np.delete(a,np.s_[3:9])
print(a)

[0 1 2 9]


2.Create random vector of size 10 and replace the maximum value by 0

In [2]:
import numpy as np
a = np.random.randint(0,100,10)
print(a)
a[np.argmax(a)]=0
print(a)

[27 92 66 88  6 61 32 92  4 31]
[27  0 66 88  6 61 32 92  4 31]


3.How to find common values between two arrays?

In [3]:
import numpy as np
a = np.arange(1,10)
b = np.arange(5,14)
print(a)
print(b)
print(np.intersect1d(a,b))

[1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13]
[5 6 7 8 9]


4.Reverse a vector (first element becomes last)

In [4]:
import numpy as np
a=np.arange(1,10)
a = a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1]


5.Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
import numpy as np
a = np.random.randint(0,9,(3,3))
print(a)

[[5 5 8]
 [1 7 4]
 [5 6 7]]


6.Find indices of non-zero elements from the array [1,2,0,0,4,0]

In [6]:
import numpy as np
a = np.array([1,2,0,0,4,0])
print(np.where(a!=0))

(array([0, 1, 4], dtype=int64),)


7.Create a 3x3x3 array with random values

In [7]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.72483152 0.52611406 0.31241075]
  [0.05145245 0.88318941 0.24127084]
  [0.39309424 0.15660484 0.2915644 ]]

 [[0.74371115 0.47246508 0.65431807]
  [0.85733239 0.76316862 0.74274358]
  [0.43603496 0.78560149 0.4447585 ]]

 [[0.09073788 0.70218111 0.34285501]
  [0.65484667 0.49290338 0.04093208]
  [0.27778358 0.34676796 0.25128785]]]


8.Create a random vector of size 30 and find the mean value

In [2]:
import numpy as np
a = np.random.random((30))
print(a)
print("gia tri trung binh: ",np.mean(a))

[0.05247972 0.28597034 0.69478    0.98428151 0.69666914 0.87577892
 0.76972369 0.02765039 0.72978542 0.39630335 0.56950178 0.17800352
 0.18801683 0.70771154 0.1912658  0.19292345 0.02553897 0.25472476
 0.15579094 0.89393799 0.81684326 0.88539083 0.47632887 0.99644047
 0.25352969 0.49344476 0.52398942 0.6613088  0.5174262  0.52665304]
gia tri trung binh:  0.5007397794791214


9.Create a 2d array with 1 on the border and 0 inside

In [12]:
import numpy as np
a = np.ones((6,6))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


10.Given an array x of 20 integers in the range (0, 100) and an random float in the range (0, 20). Find the index of x where the value at that index is closest to y.

In [1]:
import numpy as np
x = np.random.randint(0, 100, 20)
y = np.random.uniform(0, 20)
y
print(x)
print(y)
index = np.argmin(np.abs(np.array(x)-y))
print(" index of x where the value at that index is closest to y: ",index)
print(" value at that index is closest to yin x: ",x[index])

[22 37 75 37 77 83 87 49 84 92 56 56 76  2 88 58 60 62 88 73]
14.073022116131568
 index of x where the value at that index is closest to y:  0
 value at that index is closest to yin x:  22
