1. Given a 1D array, negate all elements which are between 3 and 8, in place (not created a new array).


In [1]:
import numpy as np 
a=np.arange(0,10)
a=np.delete(a,np.s_[3:9])
print(a)

[0 1 2 9]


2.Create random vector of size 10 and replace the maximum value by 0

In [2]:
import numpy as np
a = np.random.randint(0,100,10)
print(a)
a[np.argmax(a)]=0
print(a)

[27 92 66 88  6 61 32 92  4 31]
[27  0 66 88  6 61 32 92  4 31]


3. How to find common values between two arrays?

In [3]:
import numpy as np
a = np.arange(1,10)
b = np.arange(5,14)
print(a)
print(b)
print(np.intersect1d(a,b))

[1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13]
[5 6 7 8 9]


4. Reverse a vector (first element becomes last)

In [4]:
import numpy as np
a=np.arange(1,10)
a = a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1]


5. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
import numpy as np
a = np.random.randint(0,9,(3,3))
print(a)

[[5 5 8]
 [1 7 4]
 [5 6 7]]


6. Find indices of non-zero elements from the array [1,2,0,0,4,0]

In [6]:
import numpy as np
a = np.array([1,2,0,0,4,0])
print(np.where(a!=0))

(array([0, 1, 4], dtype=int64),)


7. Create a 3x3x3 array with random values

In [7]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.72483152 0.52611406 0.31241075]
  [0.05145245 0.88318941 0.24127084]
  [0.39309424 0.15660484 0.2915644 ]]

 [[0.74371115 0.47246508 0.65431807]
  [0.85733239 0.76316862 0.74274358]
  [0.43603496 0.78560149 0.4447585 ]]

 [[0.09073788 0.70218111 0.34285501]
  [0.65484667 0.49290338 0.04093208]
  [0.27778358 0.34676796 0.25128785]]]


In [ ]:
8. Create a random vector of size 30 and find the mean value

In [11]:
import numpy as np
a = np.random.random((30))
print(a)
print("gia tri trung binh: ",a.sum()/30)

[0.33182203 0.9543395  0.15048349 0.1517958  0.0360538  0.90599077
 0.05512375 0.37516767 0.69028006 0.67493622 0.92976238 0.57756742
 0.52864403 0.60726887 0.19224031 0.65662216 0.3840179  0.75426923
 0.0965804  0.17119357 0.51736265 0.29364431 0.70253466 0.41615586
 0.78616996 0.12054004 0.30183025 0.56536644 0.76258717 0.66170866]
gia tri trung binh:  0.47840197854647226


9. Create a 2d array with 1 on the border and 0 inside

In [12]:
import numpy as np
a = np.ones((6,6))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


10. Given an array x of 20 integers in the range (0, 100)

In [13]:
import numpy as np
x = np.random.randint(0, 100, 20)
print(x)

[60 82 66 87 31 96 75 69 19 31 17 74 48 24 55  8 15 52 29 86]
